export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS'
export const SHOW_RULES = 'SHOW_RULES'
export const SHOW_START_MENU = 'SHOW_START_MENU'
export const SHOW_SETTINGS = 'SHOW_SETTINGS'
export const SHOW_GAME_SETTINGS = 'SHOW_GAME_SETTINGS'

// Game Logic

export const INCREASE_PRISONERS_QTT = 'INCREASE_PRISONERS_QTT'
export const DECREASE_PRISONERS_QTT = 'DECREASE_PRISONERS_QTT'
