export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS'
export const SHOW_RULES = 'SHOW_RULES'
export const SHOW_START_MENU = 'SHOW_START_MENU'
export const SHOW_ABOUT = 'SHOW_SETTINGS'
export const SHOW_GAME_SETTINGS = 'SHOW_GAME_SETTINGS'
export const SHOW_RESET_CONFIRM_WINDOW = 'SHOW_RESET_CONFIRM_WINDOW'
export const SHOW_MAIN_MENU_CONFIRM_WINDOW = 'SHOW_MAIN_MENU_CONFIRM_WINDOW'

export const SOUND_SWITCH = 'SOUND_SWITCH'
export const VOLUME_SWITCH = 'VOLUME_SWITCH'

// Game Logic

export const INCREASE_PRISONERS_QTT = 'INCREASE_PRISONERS_QTT'
export const DECREASE_PRISONERS_QTT = 'DECREASE_PRISONERS_QTT'

export const GENERATE_BOXES = 'GENERATE_BOXES'
export const START_GAME = 'START_GAME'
export const STOP_GAME = 'STOP_GAME'

export const OPEN_BOX = 'OPEN_BOX'
